debug = false

logLevel = "INFO"
defaultEntryPoints = ["http", "https", "ws", "wss"]

[web]
# Port for the status page
address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["192.0.0.0/8", "10.0.0.0/8"]
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.forwardedHeaders]
      trustedIPs = ["192.0.0.0/8", "10.0.0.0/8"]
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
swarmmode = true
