actions:
  1:
    action: delete_indices
    description: >-
      Delete ALL indices older than 1 day
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
#    - filtertype: pattern
#      kind: regex
#      value: '^(logstash-|filebeat-).*$'
#      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 1
      exclude:
