version: "3.5"
services:
  env:
    image: php:7.3.2-apache-stretch
    hostname: ex2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ex2"
      - "traefik.frontend.rule=Host: ex2.ide"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_net"
      - "traefik.frontend.entryPoints=http"
      - "stackname=ex2"
      - "filebeat_enable=true"
    volumes:
#      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/user.ini
      - ./www:/var/www/html
    networks:
      - traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1"

networks:
  traefik:
    external: true
    name: traefik_net

