version: "3.5"
services:
  {{stack_name}}:
    image: php:7.3.2-apache-stretch
    hostname: {{stack_name}}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    labels:
      - "traefik.enable=true"
      - "traefik.backend={{stack_name}}"
      - "traefik.frontend.rule=Host: {{stack_name}}.{{hostname}}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_net"
      - "traefik.frontend.entryPoints=http"
      - "stackname={{stack_name}}"
      - "filebeat_enable=true"
    volumes:
#      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/user.ini
      - ./www:/var/www/html
	  - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1"

networks:
  traefik:
    external: true
    name: traefik_net

