version: "3.5"
services:
  {{stack_name}}:
    image: joomla:{{version}}
    hostname: {{stack_name}}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.backend={{stack_name}}"
        - "traefik.frontend.rule=Host: {{stack_name}}.{{hostname}}"
        - "traefik.port=80"
        - "traefik.docker.network=net_proxy"
        - "traefik.frontend.entryPoints=http"
        - "stackname={{stack_name}}"
        - "filebeat_enable=true"
    volumes:
      - ../../config/docker/php/php.ini:/usr/local/etc/php/conf.d/user.ini
      - ./www:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: root
      JOOMLA_DB_NAME: {{stack_name}}
    networks:
      - proxy
      - data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1"

networks:
  proxy:
    external: true
    name: net_proxy
  data:
    external: true
    name: net_data
