version: "3.5"

services:

  traefik:
    image: traefik:v1.7.20
    hostname: traefik
    ports:
      - target: 8080
        published: 8080
        mode: host
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
    networks:
      - proxy
    labels:
      - "traefik.enable=false"
      - "filebeat_enable=false"
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "1"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.role == manager
      labels:
      - "filebeat_enable=true"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=net_proxy"
      - "traefik.backend=phpmyadmin"
      - "traefik.frontend.rule=Host: pma.{{hostname}}"
      - "traefik.frontend.entryPoints=http"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - proxy
      - data
    logging:
      driver: "none"


  portainer:
    image: portainer/portainer
    hostname: portainer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.role == manager
      labels:
        - "filebeat_enable=true"
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=net_proxy"
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=Host: portainer.{{hostname}}"
        - "traefik.frontend.entryPoints=http"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../data/portainer:/data
    networks:
      - proxy
      - ide
    logging:
      driver: "none"

  mysql:
    image: mysql_ide
    hostname: mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ../../data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"
      - "filebeat_enable=true"
    networks:
      - data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1"

  env:
    image: php_ide
    hostname: env.{{hostname}}
    user: root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.backend=env"
        - "traefik.frontend.rule=Host: env.{{hostname}}"
        - "traefik.port=80"
        - "traefik.docker.network=net_proxy"
        - "traefik.frontend.entryPoints=http"
        - "stackname=env"
        - "filebeat_enable=true"
  #    environment:
  #      - APACHE_RUN_USER=root
  #      - PHP_CFLAGS=-DBIG_SECURITY_HOLE
    volumes:
      - ./php/php.ini:/usr/local/etc/php/conf.d/user.ini
      - ../../env/www:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - {{envpwd}}:{{envpwd}}
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
      - data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1"

networks:
  ide:
  proxy:
    external: true
    name: net_proxy
  data:
    external: true
    name: net_data
