#filebeat.autodiscover:
#  providers:
#    - type: docker
#      hints.enabled: true
#      json.message_key: log
#      templates:
#        - condition.contains:
##              docker.container.labels.filebeat_enable: "true"
#              docker.container.image: php_http2
#          config:
#            - type: docker
#              containers.ids:
#                - "${data.docker.container.id}"
#              json.keys_under_root: true
#              json.add_error_key: false

filebeat.inputs:
- type: docker
  hints.enabled: true
  json.message_key: log
  containers.ids:
    - '*'
  tags: ["dev.ide"]
  scan_frequency: 60s
  ignore_older: 5m
  harvester_buffer_size: 16384
  max_bytes: 10485760
  max_procs: 1

processors:
#- add_cloud_metadata: ~
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- drop_event:
    when.or:
        - and:
            - not:
                equals:
#                    docker.container.image: "php_http:latest"
                    docker.container.labels.filebeat_enable: "true"

#output.logstash:
#  hosts: ["logstash:5044"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
#    - index: "access-%{[beat.version]}-%{+yyyy.MM.dd}"
#      when.contains:
#        stream: "stdout"
#    - index: "error-%{[beat.version]}-%{+yyyy.MM.dd}"
#      when.contains:
#        stream: "stderr"
    - index: "%{[docker.container.labels.com.docker.swarm.service.name]}-%{+yyyy.MM.dd}"
